(define (problem trucker-1-package)
   (:domain trucker)
   (:objects tampines changi bedok package1 truck1)
   (:init (location tampines)
          (location changi)
          (location bedok)
          (package package1)
          (truck truck1)
          (at-loc tampines)
          (free truck1)
          (at package1 bedok))
   (:goal (and (at package1 changi))))
