(define (problem trucker-2-package)
   (:domain trucker)
   (:objects tampines changi bedok package1 package2 truck1)
   (:init (location tampines)
          (location changi)
          (location bedok)
          (package package1)
          (package package2)
          (truck truck1)
          (at-loc tampines)
          (free truck1)
          (at package1 bedok)
          (at package2 changi))
   (:goal (and (at package1 changi) (at package2 bedok))))
